interface/card/urls.py
from django.conf.urls import url
from . import views

from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from .models import Card

app_name = 'card'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^lista/', login_required(ListView.as_view(model=Card)),
		name='lista'),
	url(r'^dodaj/$',views.CardAdd.as_view(), name='dodaj'),
]

interface/interface/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
    url(r'^', include('card.urls')),
    url(r'^konta/',include('registration.backends.simple.urls')),
    url(r'^card/', include('card.urls')),
    url(r'^admin/', admin.site.urls),
]

interface/card/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

class Card(models.Model):
	nazwa = models.CharField(verbose_name='Card number', max_length=15)
	imie = models.CharField(max_length=15)
	nazwisko = models.CharField(max_length=20)
#	data = models.DateField('dodano', auto_now_add=True)
	autor = models.ForeignKey(User, on_delete=models.CASCADE)
# Create your models here.

interface/card/forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm
from . import models

class CardForm(ModelForm):

	class Meta:
		model = models.Card
		fields = ('nazwa','imie', 'nazwisko')

interface/card/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from . import models
from . import forms
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.template.response import TemplateResponse

def index(request):
	"""Strona główna"""
	kontekst = {'komunikat': 'Witaj w aplikacji Card!'}
#	return render(request, 'card/index.html', kontekst)
	return TemplateResponse(request, 'card/index.html', kontekst)
@method_decorator(login_required,'dispatch')
class CardAdd(CreateView):

	model = models.Card
	form_class = forms.CardForm
	success_url = reverse_lazy('card:lista')

	def get_context_data(self, **kwargs):
		context = super(CardAdd, self).get_context_data(**kwargs)
		return context

	def post(self, request, *args, **kwargs):
		self.object = None
		form = self.get_form()
		if form.is_valid():
			return self.form_valid(form)
		else:
			return self.form_invalid(form)

	def form_valid(self, form):
		form.instance.autor = self.request.user
		self.object = form.save()
		return HttpResponseRedirect(self.get_success_url())

	def form_invalid(self, form):
		return self.render_to_response(
			self.get_context_data(form=form)
		)
#Create your views here.

interface/card/templates/card/base.html
{% load static %}<!DOCTYPE html>
<html lang="pl">
<head>	
	<meta charset="utf-8">
	<link href="{% static 'card/css/style.css' %}" rel="stylesheet">
</head>
	
<body>

<nav class="navbar">

<ul class="nav navbar">
	<li><a href="{% url 'card:index' %}">Start</a></li>
	{% if not user.is_authenticated %}
	<li><a href="{% url 'auth_login' %}">Zaloguj</a></li>
	<li><a href="{% url 'registration_register' %}">Utwórz konto</a></li>
	{% else %}
	<li><a href="{% url 'auth_logout' %}">Wyloguj:{{ user.username }}</a></li> 
	<li><a href="{% url 'card:lista' %}">Lista kart</a></li>
	<li><a href="{% url 'card:dodaj' %}">Dodaj kartę</a></li>
	{% endif %}
</ul>

</nav>

<div class="container">

	<h1>{% block tytul_h1 %}{% endblock %}</h1>
<div class="tresc">
	{% block tresc %}{% endblock %}
</div>

</body>
</html>

interface/card/templates/card/card_form.html
{% extends "card/base.html" %}

{% block tytul_h1 %}
	Dodaj kartę
{% endblock %}

{% block tresc %}
<form action="." method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Zapisz">
</form>
{% endblock %}

interface/card/templates/card/card_list.html
{% extends "card/base.html"%}

{% block tytul_h1 %}
Lista kart
{% endblock %}

{% block tresc %}
<table class="table">
	<tr>
		<th>Lp.</th><th>Numer karty</th><th>Imie</th><th>Nazwisko</th>
		<th>Autor</th>
		<th>Info</th>

	</tr>
	{% for p in object_list %}
	<tr>
		<td>{{ forloop.counter }}</td>
		<td>{{ p.nazwa }}</td>
		<td>{{ p.imie }}</td>
		<td>{{ p.nazwisko }}</td>
		<td>{{ p.autor }}</td>		
		<td>
			<a href="#">Edytuj</a>
			<a href="#">Usuń</a>
		</td>
	</tr>
	{% endfor %}	


</table>
{% endblock %}

interface/card/templates/card/index.html
{% extends "card/base.html" %}

{% block tytul_h1 %}
Interdyscyplinarne Centrum Modelowania Matematycznego i Komputerowego
{% endblock %}

{% block tresc %}
<p>{{komunikat}}</p>
{% endblock %}